TypeError: exceptions must derive from BaseException
Wouldn't show the actual error due to an error in the throw:
```
Traceback (most recent call last):
  File "P:\goonstation\tools\ci\validate_dme.py", line 90, in compare_lines
    raise f"Two lines were exactly the same ({a} vs. {b})"
TypeError: exceptions must derive from BaseException
```