New morbid tools (#91614)
## About The Pull Request

New morbid themed tools to fill out the full suite.

Includes:

tearing drill: morbid variant of the surgical drill. Sprite is recolored
from a standard surgical drill.
jagged bonesaw: morbid variant of the surgical saw. Sprite is a
recolored and slightly edited bonesaw from skyrat. The overlay sprite
for this was made from the ground up by myself
harsh bonesetter: morbid variant of the bonesetter. Sprite is a
recolored bonesetter.
malignant blood filter: morbid variant of the blood filter. Sprite is a
recolored blood filter.

All tools function basically identically to normal tools with 1
exception: They all have the cruel tag, so are best used on the dead
rather then the living. The malevolent autopsy scanner is slightly
faster at performing autopsies...but only if you have the morbid trait.

All sprites and overlays were created by myself.

All item descriptions were created by myself, feedback is welcomed and
encouraged! If you feel that there is a better description for them
please do share.

Also includes:
All tools added to the coroner's wardrobe
All tools replaced in the coroner's surgical tray with the new
appropriately themed variants.
Adds the CRUEL_IMPLEMENT tag to the autopsy scanner, letting coroners do
the autopsy surgery faster

## Why It's Good For The Game

I always felt it strange that the coroner didn't have a full suite of
themed tools, so I set out to fix that. This both helps encourage the
coroner to use their special tools and work with cadavers more
efficiently. It also further solidifies coroner's role in working with
the dead, and lets them show that they are the best at autopsies.


## Changelog

:cl:
add: Adds new morbid themed tools for the coroners enjoyment. Coroners
now perform autopsies slightly faster.
/:cl:


![image](https://github.com/user-attachments/assets/70a84aad-61c4-435a-a7b1-96922fd9d2b9)

![image](https://github.com/user-attachments/assets/a95f29d0-3ade-485f-9f89-2109d81ad743)